
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: istory_development

test: &test
  <<: *default
  database: istory_test

production:
  <<: *default
  database: istory_production
  username: istory
  password: <%= ENV['ISTORY_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
